// UI strings live here (Greek; F1 terms stay English, as on f1stories.gr). Components migrate in as each rework phase touches them.
export const copy = {
  locale: 'el-GR',
  tabs: {
    telemetry: 'Τηλεμετρία',
    tires: 'Ελαστικά',
    energy: 'DRS & RPM',
    trackmap: 'Track Map',
    positions: 'Θέσεις',
    intervals: 'Intervals',
    radio: 'Team Radio',
    incidents: 'Race Control',
    weather: 'Καιρός',
    broadcast: 'Broadcast',
  },
  skipToContent: 'Μετάβαση στο περιεχόμενο',
  masthead: {
    homeAria: 'F1 Stories, αρχική σελίδα',
    menu: 'Μενού',
    tools: 'Εργαλεία',
    themeToLight: 'Φωτεινό θέμα',
    themeToDark: 'Σκούρο θέμα',
    themeOnLight: 'Φωτεινό θέμα ενεργό',
    themeOnDark: 'Σκούρο θέμα ενεργό',
    back: 'Πίσω',
    print: 'Εκτύπωση',
    split: 'Διπλή προβολή',
    presetLabel: 'Αποθήκευση ή φόρτωση σύγκρισης',
    presetPlaceholder: 'Όνομα σύγκρισης',
    save: 'Αποθήκευση',
    nextSession: 'Επόμενο GP',
    presetLoaded: (name: string) => `Φορτώθηκε η σύγκριση ${name}`,
    presetSaved: (name: string) => `Αποθηκεύτηκε η σύγκριση ${name}`,
    printing: 'Άνοιγμα διαλόγου εκτύπωσης',
    splitEnabled: 'Ενεργοποιήθηκε η διπλή προβολή',
    splitDisabled: 'Απενεργοποιήθηκε η διπλή προβολή',
    noHistory: 'Δεν υπάρχει προηγούμενη σελίδα στο ιστορικό',
  },
  hero: {
    kicker: 'F1 Stories / Race Desk',
    descriptor: 'Τηλεμετρία & ανάλυση γύρου',
    title: 'Telemetry',
    tagline: 'Κάθε γύρος, μια ιστορία.',
    taglineBody: 'Ταχύτητα, φρένα, sectors και στρατηγική για κάθε οδηγό. Σύγκρινε έως τέσσερις.',
    lap: (lap: number, total: number) => (total > 0 ? `Γύρος ${lap} από ${total}` : `Γύρος ${lap}`),
  },
  band: {
    live: 'Live δεδομένα · OpenF1',
    lap: (lap: number, total: number) => (total > 0 ? `Γύρος ${lap} / ${total}` : `Γύρος ${lap}`),
    slogan: 'Every tenth counts.',
    loading: 'Φόρτωση συνεδρίας…',
    partial: (loaded: number, total: number) => `${loaded} / ${total} οδηγοί φορτώθηκαν`,
    retry: (name: string) => `Επανάληψη ${name}`,
  },
  scope: {
    label: 'Πεδίο ανάλυσης',
    season: 'Σεζόν',
    grandPrix: 'Grand Prix',
    session: 'Συνεδρία',
    lap: (total: number | null) => (total ? `Γύρος / ${total}` : 'Γύρος'),
    lapOption: (lap: number) => `Γύρος ${lap}`,
    prevLap: 'Προηγούμενος γύρος',
    nextLap: 'Επόμενος γύρος',
    loadingCircuits: 'Φόρτωση πίστας…',
    noData: (year: number) => `Δεν υπάρχουν δεδομένα για το ${year}`,
    loadingSessions: 'Φόρτωση συνεδριών…',
    selectGp: 'Επίλεξε πρώτα GP',
    loadingLaps: 'Φόρτωση…',
    selectDrivers: 'Επίλεξε οδηγούς',
    drivers: 'Οδηγοί',
    add: '+ Προσθήκη',
    close: 'Κλείσιμο',
    rosterHelp: 'Επίλεξε έως τέσσερις οδηγούς. Ο πέμπτος αντικαθιστά τον πρώτο· κράτα τουλάχιστον έναν.',
  },
  lapStrip: {
    title: (driver: string) => `Χρόνοι γύρου · ${driver}`,
    safetyCar: 'Safety car',
    selected: (lap: number) => `Γύρος ${lap}`,
    bar: (lap: number, time: string | null, note: string | null) => [`Γύρος ${lap}`, time, note].filter(Boolean).join(', '),
    pit: 'Pit stop',
  },
  panel: {
    menu: 'Ενέργειες γραφήματος',
    embed: 'Ενσωμάτωση',
    download: 'Λήψη',
    fullScreen: 'Πλήρης οθόνη',
    exitFull: 'Έξοδος',
  },
  cardBar: {
    title: (tab: string) => `Καρτέλα ${tab}`,
    caption: 'Ο κοινόχρηστος σύνδεσμος κρατά τη σεζόν, τον αγώνα, τον γύρο και τους οδηγούς.',
    share: 'Κοινοποίηση καρτέλας',
    embed: 'Ενσωμάτωση καρτέλας',
  },
  summary: {
    reference: 'Reference',
    gap: 'Διαφορά',
    topSpeed: 'Top speed',
    driverLap: (driver: string) => driver,
  },
  gapCard: {
    who: (target: string, reference: string) => `${target} · απόσταση από ${reference}`,
    sub: (lapTime: string, topSpeed: number | null) => [lapTime, topSpeed != null ? `top speed ${Math.round(topSpeed)} km/h` : null].filter(Boolean).join(' · '),
    slow: 'Αργές στροφές',
    medium: 'Μεσαίες στροφές',
    fast: 'Ευθείες',
    source: 'Πηγή / OpenF1 · car_data',
    label: 'Απόσταση από τον ταχύτερο γύρο',
  },
  chart: {
    source: 'Πηγή: OpenF1',
    sourceCarData: 'Πηγή: OpenF1 car_data · κανονικοποιημένο ανά πρόοδο γύρου',
    cornerNote: 'Οι κάθετες γραμμές δείχνουν τις πιο αργές στροφές του γύρου.',
    corner: (n: number) => `C${n}`,
  },
  radio: {
    listen: 'Άκουσε την ηχογράφηση',
    listenAria: (driver: string, time: string) => `Άκουσε την ηχογράφηση του ${driver} στις ${time}`,
  },
  embed: {
    open: 'Άνοιξε την ανάλυση ↗', title: 'Δημιουργία σχήματος τηλεμετρίας', close: 'Κλείσιμο',
    panel: 'Γράφημα', titleLabel: 'Τίτλος', description: 'Προσβάσιμη περιγραφή', caption: 'Λεζάντα',
    selectPanel: 'Επίλεξε γράφημα', speed: 'Ταχύτητα', pedals: 'Γκάζι και φρένο',
    scope: 'Αποθηκευμένο πεδίο', preview: 'Προεπισκόπηση στενού σχήματος',
    widePreview: 'Ευρεία προεπισκόπηση', context: 'Πλαίσιο', source: 'OpenF1 · σταθερό στιγμιότυπο δεδομένων',
    complete: 'Τα δεδομένα είναι πλήρη για όλους τους επιλεγμένους οδηγούς.',
    partial: (names: string) => `Λείπουν δεδομένα για: ${names}. Δήλωσε ότι η σύγκριση είναι μερική για να συνεχίσεις.`,
    acknowledge: 'Κατανοώ ότι το δημοσιευμένο γράφημα έχει ελλιπή δεδομένα',
    download: 'Λήψη πακέτου δημοσίευσης', exporting: 'Δημιουργία τεσσάρων εικόνων…',
    marker: 'Αντιγραφή δείκτη άρθρου', markerHelp: 'Τοποθέτησε το πακέτο δίπλα στο άρθρο ή στον φάκελο embeds και πρόσθεσε τον δείκτη.',
    captionRequired: 'Πρόσθεσε μια λεζάντα που εξηγεί τι δείχνει το γράφημα ή πώς διαβάζεται.',
    copied: 'Ο δείκτης αντιγράφηκε', copyFailed: 'Η αυτόματη αντιγραφή απέτυχε. Επίλεξε και αντέγραψε τον δείκτη.',
    bundleReady: 'Το πακέτο δημοσίευσης λήφθηκε', missingScope: 'Επίλεξε επιβεβαιωμένη συνεδρία, γύρο και οδηγούς πριν από την εξαγωγή.',
    noPlot: 'Δεν υπάρχουν ολοκληρωμένα δεδομένα γραφήματος για αποθήκευση.',
    legacy: 'Παλαιού τύπου iframe', legacyCopy: 'Αντιγραφή κώδικα iframe', legacyHelp: 'Για μη υποστηριζόμενα γραφήματα ή παλαιότερες σελίδες.',
    unsupported: 'Αυτό το γράφημα δεν υποστηρίζεται ακόμη ως αποθηκευμένο σχήμα. Χρησιμοποίησε τον σύνδεσμο πλήρους ανάλυσης ή το παλαιού τύπου iframe.',
    chooseFigure: 'Επίλεξε ένα από τα υποστηριζόμενα γραφήματα για να συνεχίσεις.',
    waiting: 'Περίμενε να ολοκληρωθούν οι λήψεις της επιλεγμένης συνεδρίας και του γύρου πριν από τη δημοσίευση.',
    exportError: (reason: string) => `Η εξαγωγή απέτυχε: ${reason}. Το πρόχειρο διατηρήθηκε· διόρθωσε το πεδίο και δοκίμασε ξανά.`,
  },
  weather: { track: 'Πίστα', air: 'Αέρας', humidity: 'Υγρασία', wind: 'Άνεμος' },
  next: {
    label: 'Επόμενες προβολές',
    hints: {
      telemetry: 'Ταχύτητα & πεντάλ',
      energy: 'DRS, ταχύτητες & στροφές',
      trackmap: 'Ποιος κερδίζει πού',
      positions: 'Γύρο προς γύρο',
      intervals: 'Διαφορές & DRS',
      tires: 'Stints & pit stops',
      radio: 'Οι ηχογραφήσεις',
      incidents: 'Σημαίες & ποινές',
      weather: 'Πίστα, αέρας, υγρασία',
      broadcast: 'Ταξινόμηση γύρου',
    },
  },
  footer: {
    tagline: 'Τεχνική ανάλυση, άποψη και ελληνική F1 κοινότητα.',
    credit: 'Δεδομένα από OpenF1',
    rights: `© ${new Date().getFullYear()} F1 Stories. Με επιφύλαξη παντός δικαιώματος.`,
    privacy: 'Πολιτική Απορρήτου',
    terms: 'Όροι Χρήσης',
  },
} as const;

// Mirrors f1StoriesPage/partials/nav.html. If the site nav changes, update this list too.
const AGGREGATED = import.meta.env.VITE_F1STORIES_BUILD === 'true';
export const SITE = AGGREGATED ? '' : 'https://f1stories.gr';
const BETCAST = AGGREGATED ? '/betcast/' : 'https://georgiosbalatzis.github.io/BetCastVisualisation/';
export const SITE_NAV = [
  { label: 'Αρχική', href: `${SITE}/` },
  { label: 'Άρθρα', href: `${SITE}/blog-module/blog/index.html` },
  { label: 'YouTube', href: 'https://www.youtube.com/@f1_stories_original', external: true },
  { label: 'Βαθμολογία', href: `${SITE}/standings/` },
  { label: 'Δεδομένα', href: `${SITE}/standings/?tab=tyre-pace`, current: true }, // Telemetry is part of Race Desk
  { label: 'Συντάκτες', href: `${SITE}/authors/` },
  { label: 'BetCast', href: BETCAST, external: !AGGREGATED },
] as const;

// Race Desk product switcher, per f1StoriesPage/docs/race-desk-architecture.md: same order and same-tab links on every
// product. All Race Desk products share the canonical origin.
export const RACE_DESK_NAV = [
  { label: 'THE GRID', href: `${SITE}/standings/` },
  { label: 'TELEMETRY', href: import.meta.env.BASE_URL, current: true },
  { label: 'GHOST CAR', href: AGGREGATED ? '/ghostcar/' : 'https://georgiosbalatzis.github.io/ghostcar/' },
  { label: 'TYRES', href: AGGREGATED ? '/tyres/' : 'https://georgiosbalatzis.github.io/Tyres/' },
] as const;

// Footer links from f1StoriesPage/partials/footer.html.
export const SITE_FOOTER_LINKS = [
  { label: 'Άρθρα', href: `${SITE}/blog-module/blog/index.html` },
  { label: 'Βαθμολογία', href: `${SITE}/standings/` },
  { label: 'Συντάκτες', href: `${SITE}/authors/` },
  { label: 'YouTube ↗', href: 'https://www.youtube.com/@f1_stories_original', external: true },
  { label: 'BetCast ↗', href: BETCAST, external: !AGGREGATED },
] as const;
export const SITE_SOCIAL_LINKS = [
  { label: 'F1 Stories στο YouTube', href: 'https://www.youtube.com/@f1_stories_original', icon: 'fa-youtube' },
  { label: 'F1 Stories στο Facebook', href: 'https://www.facebook.com/f1storiess', icon: 'fa-facebook-f' },
  { label: 'F1 Stories στο Instagram', href: 'https://www.instagram.com/myf1stories/', icon: 'fa-instagram' },
  { label: 'F1 Stories στο TikTok', href: 'https://www.tiktok.com/@f1stories6', icon: 'fa-tiktok' },
  { label: 'Email στο F1 Stories', href: 'mailto:myf1stories@gmail.com', icon: 'fa-envelope' },
] as const;
export const SITE_LEGAL = { home: `${SITE}/`, privacy: `${SITE}/privacy/privacy.html`, terms: `${SITE}/privacy/terms.html` } as const;
